-- MySQL Script generated by MySQL Workbench
-- 10/15/16 17:54:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsec
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbsec` ;

-- -----------------------------------------------------
-- Schema dbsec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsec` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `dbsec` ;

-- -----------------------------------------------------
-- Table `dbsec`.`vote_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsec`.`vote_session` ;

CREATE TABLE IF NOT EXISTS `dbsec`.`vote_session` (
  `id` INT NOT NULL,
  `creationdate` DATETIME NULL,
  `viewingdate` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `viewingdate_UNIQUE` (`viewingdate` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsec`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsec`.`film` ;

CREATE TABLE IF NOT EXISTS `dbsec`.`film` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `year` INT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsec`.`film_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsec`.`film_session` ;

CREATE TABLE IF NOT EXISTS `dbsec`.`film_session` (
  `session_id` INT NULL,
  `film_id` INT NULL,
  `id` INT NOT NULL,
  INDEX `film_id_idx` (`film_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `session_id_idx` (`session_id` ASC),
  CONSTRAINT `fk_film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `dbsec`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_id`
    FOREIGN KEY (`session_id`)
    REFERENCES `dbsec`.`vote_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsec`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsec`.`member` ;

CREATE TABLE IF NOT EXISTS `dbsec`.`member` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsec`.`member_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsec`.`member_session` ;

CREATE TABLE IF NOT EXISTS `dbsec`.`member_session` (
  `film_session_id` INT NULL,
  `member_id` INT NULL,
  INDEX `film_session_id_idx` (`film_session_id` ASC),
  INDEX `fk_member_id_idx` (`member_id` ASC),
  CONSTRAINT `fk_film_session_id`
    FOREIGN KEY (`film_session_id`)
    REFERENCES `dbsec`.`film_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `dbsec`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsec`.`system_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsec`.`system_parameter` ;

CREATE TABLE IF NOT EXISTS `dbsec`.`system_parameter` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idsystem_parameter_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
